# Generated by Django 3.1.2 on 2020-10-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20201015_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile/img'),
        ),
    ]
