# Generated by Django 3.1.2 on 2020-10-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
