# Generated by Django 3.1.2 on 2020-10-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_auto_20201012_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='decription',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
