# Generated by Django 3.1.2 on 2020-10-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_auto_20201012_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
