# Generated by Django 3.1.2 on 2020-10-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0005_categore'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Categore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Job.categore'),
            preserve_default=False,
        ),
    ]
