# Generated by Django 3.1.2 on 2020-10-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_job_categore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Categore',
            new_name='categore',
        ),
    ]
