# Generated by Django 3.1.2 on 2020-10-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_auto_20201012_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField(default=1, upload_to='job/'),
            preserve_default=False,
        ),
    ]
