# Generated by Django 3.1.2 on 2020-10-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0008_job_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
