# Generated by Django 3.1.2 on 2020-10-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0011_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='Apply_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
