# Generated by Django 3.1.2 on 2020-10-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0012_apply_apply_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='converletter',
            field=models.TextField(),
        ),
    ]
